[project]
name = "hdc-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.1.1",
    "ipykernel>=6.30.1",
    "numpy>=2.3.3",
    "pytest>=8.4.2",
    "tqdm>=4.67.1",
]
